# Generated by Django 4.2.6 on 2023-10-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='Username',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
