# Generated by Django 4.2.6 on 2023-10-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminStaff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminstaff',
            name='Username',
            field=models.CharField(max_length=50),
        ),
    ]
